### ISSUE TITLE
Intermittent test failure in folder reprocessing

### ISSUE THREAD

**Issue by simong** [oaeproject/Hilary#1084]
See https://travis-ci.org/oaeproject/Hilary/builds/40199911 and S3 logs at oae-testing/travisci/logs/hilary/build-2138-33cba0f68c755c73f434dea7659325197b48bace-Thu Nov 06 2014 17:09:33 GMT+0000 (UTC).log.gz

>   1202 passing (13m)
  2 failing
  1) Folders Indexing verify folders can be reindexed:
     Uncaught AssertionError: 0 === 1
      at /home/travis/build/oaeproject/Hilary/node_modules/oae-folders/lib/test/util.js:1009:16
      at /home/travis/build/oaeproject/Hilary/node_modules/oae-search/lib/test/util.js:81:28
      at Request._callback (/home/travis/build/oaeproject/Hilary/node_modules/oae-rest/lib/util.js:9:8822)
      at Request.self.callback (/home/travis/build/oaeproject/Hilary/node_modules/oae-rest/node_modules/request/request.js:121:22)
      at Request.emit (events.js:98:17)
      at Request.<anonymous> (/home/travis/build/oaeproject/Hilary/node_modules/oae-rest/node_modules/request/request.js:978:14)
      at Request.emit (events.js:117:20)
      at IncomingMessage.<anonymous> (/home/travis/build/oaeproject/Hilary/node_modules/oae-rest/node_modules/request/request.js:929:12)
      at IncomingMessage.emit (events.js:117:20)
      at _stream_readable.js:938:16
  2) Preview processor Preview generation verify folder processing:
     Uncaught AssertionError: "undefined" == true
      at /home/travis/build/oaeproject/Hilary/node_modules/oae-preview-processor/tests/test-previews.js:1576:64
      at /home/travis/build/oaeproject/Hilary/node_modules/oae-folders/lib/test/util.js:440:16
      at Request._callback (/home/travis/build/oaeproject/Hilary/node_modules/oae-rest/lib/util.js:9:8822)
      at Request.self.callback (/home/travis/build/oaeproject/Hilary/node_modules/oae-rest/node_modules/request/request.js:121:22)
      at Request.emit (events.js:98:17)
      at Request.<anonymous> (/home/travis/build/oaeproject/Hilary/node_modules/oae-rest/node_modules/request/request.js:978:14)
      at Request.emit (events.js:117:20)
      at IncomingMessage.<anonymous> (/home/travis/build/oaeproject/Hilary/node_modules/oae-rest/node_modules/request/request.js:929:12)
      at IncomingMessage.emit (events.js:117:20)
      at _stream_readable.js:938:16

**Comment by simong** [comment]
I think this has been fixed now
