### ISSUE TITLE
running oae-email tests in isolation fails

### ISSUE THREAD

**Issue by stuartf** [oaeproject/Hilary#1110]
running the full test suite passes but running `grunt test-module:oae-email` fails:

    3 failing
    
    1) Emails Email configuration verify noreply from header:
       Uncaught AssertionError: false == true
        at /home/stuart/src/hilary/node_modules/oae-email/tests/test-email.js:411:36
        at /home/stuart/src/hilary/node_modules/oae-email/lib/test/util.js:105:32
        at allDone (/home/stuart/src/hilary/node_modules/oae-activity/lib/internal/email.js:201:20)
        at /home/stuart/src/hilary/node_modules/oae-activity/lib/internal/buckets.js:119:16
        at _collectBuckets (/home/stuart/src/hilary/node_modules/oae-activity/lib/internal/buckets.js:138:16)
        at /home/stuart/src/hilary/node_modules/oae-activity/lib/internal/buckets.js:149:16
        at /home/stuart/src/hilary/node_modules/oae-activity/lib/internal/buckets.js:215:28
        at /home/stuart/src/hilary/node_modules/redback/lib/advanced_structures/Lock.js:80:20
        at b (domain.js:183:18)
        at try_callback (/home/stuart/src/hilary/node_modules/redis/index.js:592:9)
    
    2) Emails Spam Prevention verify emails have a trustworthy message id:
       Uncaught AssertionError: false == true
        at /home/stuart/src/hilary/node_modules/oae-email/tests/test-email.js:466:32
        at /home/stuart/src/hilary/node_modules/oae-email/lib/test/util.js:105:32
        at allDone (/home/stuart/src/hilary/node_modules/oae-activity/lib/internal/email.js:201:20)
        at /home/stuart/src/hilary/node_modules/oae-activity/lib/internal/buckets.js:119:16
        at _collectBuckets (/home/stuart/src/hilary/node_modules/oae-activity/lib/internal/buckets.js:138:16)
        at /home/stuart/src/hilary/node_modules/oae-activity/lib/internal/buckets.js:149:16
        at /home/stuart/src/hilary/node_modules/oae-activity/lib/internal/buckets.js:215:28
        at /home/stuart/src/hilary/node_modules/redback/lib/advanced_structures/Lock.js:80:20
        at b (domain.js:183:18)
        at try_callback (/home/stuart/src/hilary/node_modules/redis/index.js:592:9)
    
    3) Emails Spam Prevention verify emails have a userid in their message id:
       Uncaught AssertionError: false == true
        at /home/stuart/src/hilary/node_modules/oae-email/tests/test-email.js:491:32
        at /home/stuart/src/hilary/node_modules/oae-email/lib/test/util.js:105:32
        at allDone (/home/stuart/src/hilary/node_modules/oae-activity/lib/internal/email.js:201:20)
        at /home/stuart/src/hilary/node_modules/oae-activity/lib/internal/buckets.js:119:16
        at _collectBuckets (/home/stuart/src/hilary/node_modules/oae-activity/lib/internal/buckets.js:138:16)
        at /home/stuart/src/hilary/node_modules/oae-activity/lib/internal/buckets.js:149:16
        at /home/stuart/src/hilary/node_modules/oae-activity/lib/internal/buckets.js:215:28
        at /home/stuart/src/hilary/node_modules/redback/lib/advanced_structures/Lock.js:80:20
        at b (domain.js:183:18)
        at try_callback (/home/stuart/src/hilary/node_modules/redis/index.js:592:9)

**Comment by nicolaasmatthijs** [comment]
Assigning to @stuartf for fix
