### ISSUE TITLE
running oae-following tests in isolation fails

### ISSUE THREAD

**Issue by stuartf** [oaeproject/Hilary#1111]
running the full test suite works, but `grunt test-module:oae-following` fails:

    2 failing
    
    1) Following Activity verify user gets notification and email when a user follows them:
       Uncaught AssertionError: 0 == 1
        at /home/stuart/src/hilary/node_modules/oae-following/tests/test-activity.js:362:28
        at /home/stuart/src/hilary/node_modules/oae-email/lib/test/util.js:105:32
        at allDone (/home/stuart/src/hilary/node_modules/oae-activity/lib/internal/email.js:201:20)
        at /home/stuart/src/hilary/node_modules/oae-activity/lib/internal/buckets.js:119:16
        at _collectBuckets (/home/stuart/src/hilary/node_modules/oae-activity/lib/internal/buckets.js:138:16)
        at /home/stuart/src/hilary/node_modules/oae-activity/lib/internal/buckets.js:149:16
        at /home/stuart/src/hilary/node_modules/oae-activity/lib/internal/buckets.js:215:28
        at /home/stuart/src/hilary/node_modules/redback/lib/advanced_structures/Lock.js:80:20
        at b (domain.js:183:18)
        at try_callback (/home/stuart/src/hilary/node_modules/redis/index.js:592:9)
    
    2) Following Activity verify users get a single aggregated activity in their email when 1 or multiple users follow them:
       Uncaught AssertionError: 0 == 1
        at /home/stuart/src/hilary/node_modules/oae-following/tests/test-activity.js:420:32
        at /home/stuart/src/hilary/node_modules/oae-email/lib/test/util.js:105:32
        at allDone (/home/stuart/src/hilary/node_modules/oae-activity/lib/internal/email.js:201:20)
        at /home/stuart/src/hilary/node_modules/oae-activity/lib/internal/buckets.js:119:16
        at _collectBuckets (/home/stuart/src/hilary/node_modules/oae-activity/lib/internal/buckets.js:138:16)
        at /home/stuart/src/hilary/node_modules/oae-activity/lib/internal/buckets.js:149:16
        at /home/stuart/src/hilary/node_modules/oae-activity/lib/internal/buckets.js:215:28
        at /home/stuart/src/hilary/node_modules/redback/lib/advanced_structures/Lock.js:80:20
        at b (domain.js:183:18)
        at try_callback (/home/stuart/src/hilary/node_modules/redis/index.js:592:9)

**Comment by nicolaasmatthijs** [comment]
Assigning to @stuartf for fix
