### ISSUE TITLE
running oae-principals tests in isolation fails

### ISSUE THREAD

**Issue by stuartf** [oaeproject/Hilary#1112]
running the full test suite works, but `grunt test-module:oae-principals` fails:

    3 failing
    
    1) Principals Activity Emails verify group-create email and privacy:
       Uncaught AssertionError: 0 == 1
        at /home/stuart/src/hilary/node_modules/oae-principals/tests/test-activity.js:872:40
        at /home/stuart/src/hilary/node_modules/oae-email/lib/test/util.js:105:32
        at allDone (/home/stuart/src/hilary/node_modules/oae-activity/lib/internal/email.js:201:20)
        at /home/stuart/src/hilary/node_modules/oae-activity/lib/internal/buckets.js:119:16
        at _collectBuckets (/home/stuart/src/hilary/node_modules/oae-activity/lib/internal/buckets.js:138:16)
        at /home/stuart/src/hilary/node_modules/oae-activity/lib/internal/buckets.js:149:16
        at /home/stuart/src/hilary/node_modules/oae-activity/lib/internal/buckets.js:215:28
        at /home/stuart/src/hilary/node_modules/redback/lib/advanced_structures/Lock.js:80:20
        at b (domain.js:183:18)
        at try_callback (/home/stuart/src/hilary/node_modules/redis/index.js:592:9)
    
    2) Principals Activity Emails verify group-join email and privacy:
       Uncaught AssertionError: 0 == 1
        at /home/stuart/src/hilary/node_modules/oae-principals/tests/test-activity.js:943:48
        at /home/stuart/src/hilary/node_modules/oae-email/lib/test/util.js:105:32
        at allDone (/home/stuart/src/hilary/node_modules/oae-activity/lib/internal/email.js:201:20)
        at /home/stuart/src/hilary/node_modules/oae-activity/lib/internal/buckets.js:119:16
        at _collectBuckets (/home/stuart/src/hilary/node_modules/oae-activity/lib/internal/buckets.js:138:16)
        at /home/stuart/src/hilary/node_modules/oae-activity/lib/internal/buckets.js:149:16
        at /home/stuart/src/hilary/node_modules/oae-activity/lib/internal/buckets.js:215:28
        at /home/stuart/src/hilary/node_modules/redback/lib/advanced_structures/Lock.js:80:20
        at b (domain.js:183:18)
        at try_callback (/home/stuart/src/hilary/node_modules/redis/index.js:592:9)
    
    3) Principals Activity Emails verify group-add-member email and privacy:
       Uncaught AssertionError: 0 == 1
        at /home/stuart/src/hilary/node_modules/oae-principals/tests/test-activity.js:1074:48
        at /home/stuart/src/hilary/node_modules/oae-email/lib/test/util.js:105:32
        at allDone (/home/stuart/src/hilary/node_modules/oae-activity/lib/internal/email.js:201:20)
        at /home/stuart/src/hilary/node_modules/oae-activity/lib/internal/buckets.js:119:16
        at _collectBuckets (/home/stuart/src/hilary/node_modules/oae-activity/lib/internal/buckets.js:138:16)
        at /home/stuart/src/hilary/node_modules/oae-activity/lib/internal/buckets.js:149:16
        at /home/stuart/src/hilary/node_modules/oae-activity/lib/internal/buckets.js:215:28
        at /home/stuart/src/hilary/node_modules/redback/lib/advanced_structures/Lock.js:80:20
        at b (domain.js:183:18)
        at try_callback (/home/stuart/src/hilary/node_modules/redis/index.js:592:9)

**Comment by nicolaasmatthijs** [comment]
Assigning to @stuartf for fix
