### ISSUE TITLE
Intermittent test failure in activity email

### ISSUE THREAD

**Issue by mrvisser** [oaeproject/Hilary#1134]
https://travis-ci.org/oaeproject/Hilary/builds/53051441

```
1219 passing (14m)
  1 failing
  1) Activity Email verify sending emails uses the configured tenant default timezone:
     Uncaught AssertionError: "jWm74iXFq5fZ@example.com" == "Wc59dNF2zEi9@example.com"
      at /home/travis/build/oaeproject/Hilary/node_modules/oae-activity/tests/test-email.js:437:40
      at /home/travis/build/oaeproject/Hilary/node_modules/oae-email/lib/test/util.js:105:32
      at allDone (/home/travis/build/oaeproject/Hilary/node_modules/oae-activity/lib/internal/email.js:9:9781)
      at /home/travis/build/oaeproject/Hilary/node_modules/oae-activity/lib/internal/buckets.js:9:3854
      at _collectBuckets (/home/travis/build/oaeproject/Hilary/node_modules/oae-activity/lib/internal/buckets.js:9:4310)
      at /home/travis/build/oaeproject/Hilary/node_modules/oae-activity/lib/internal/buckets.js:9:5051
      at /home/travis/build/oaeproject/Hilary/node_modules/oae-activity/lib/internal/buckets.js:9:8270
      at /home/travis/build/oaeproject/Hilary/node_modules/redback/lib/advanced_structures/Lock.js:80:20
      at b (domain.js:183:18)
      at try_callback (/home/travis/build/oaeproject/Hilary/node_modules/redis/index.js:592:9)
```

```
$ bin/upload_logs
Uploaded "tests.log.gz" to Amazon S3: "oae-testing/travisci/logs/hilary/build-2258-e4dd4d940f593167cb43d97a36d488c0b483290f-Wed Mar 04 2015 15:12:35 GMT+0000 (UTC).log.gz"
```

**Comment by nicolaasmatthijs** [comment]
@mrvisser : Did the intermittent test failures PR provide a solution for this?

**Comment by mrvisser** [comment]
@nicolaasmatthijs I had a look at this and it's unlikely.

**Comment by nicolaasmatthijs** [comment]
Okay, leaving this ticket open

**Comment by brecke** [comment]
Update: I've ran tests countless times over the last 5 years and I can confidently say this doesn't happen anymore.
