### ISSUE TITLE
Intermittent test failure in searching for folders by essages

### ISSUE THREAD

**Issue by simong** [oaeproject/Hilary#1156]
Part of the never-ending quest against intermittent test failures.

See https://travis-ci.org/oaeproject/Hilary/builds/55829153 for more info
```
  1259 passing (16m)
  1 failing
  1) Folders Searching for folders verify folders can be searched by messages:
     Uncaught AssertionError: false == true
      at /home/travis/build/oaeproject/Hilary/node_modules/oae-folders/lib/test/util.js:1094:16
      at Function._.each._.forEach (/home/travis/build/oaeproject/Hilary/node_modules/underscore/underscore.js:145:9)
      at _assertSearchResults (/home/travis/build/oaeproject/Hilary/node_modules/oae-folders/lib/test/util.js:1093:7)
      at /home/travis/build/oaeproject/Hilary/node_modules/oae-folders/lib/test/util.js:1035:9
      at /home/travis/build/oaeproject/Hilary/node_modules/oae-search/lib/test/util.js:163:32
      at Request._callback (/home/travis/build/oaeproject/Hilary/node_modules/oae-rest/lib/util.js:9:8822)
      at Request.self.callback (/home/travis/build/oaeproject/Hilary/node_modules/oae-rest/node_modules/request/request.js:121:22)
      at Request.emit (events.js:98:17)
      at Request.<anonymous> (/home/travis/build/oaeproject/Hilary/node_modules/oae-rest/node_modules/request/request.js:978:14)
      at Request.emit (events.js:117:20)
Warning: Task "mocha-hack:all" failed. Use --force to continue.
Aborted due to warnings.
The command "grunt test-coverage-coveralls" exited with 3.
after_failure.1
15.98s$ gzip tests.log
after_failure.2
29.12s$ bin/upload_logs
Uploaded "tests.log.gz" to Amazon S3: "oae-testing/travisci/logs/hilary/build-2326-51faa2d00eb28c8154d9b6dae275bda9e228a755-Wed Mar 25 2015 17:47:25 GMT+0000 (UTC).log.gz"
```

**Comment by nicolaasmatthijs** [comment]
@mrvisser : Did the intermittent test failures PR provide a solution for this?

**Comment by mrvisser** [comment]
It's hard to tell without downloading and analyzing the log file posted, but I'd say there is a good chance that it did, as I fixed quite a few intermittent failure issues in folders. I'll close this until something else crops up.
