### ISSUE TITLE
Cassandra 2.2+ compatibility

### ISSUE THREAD

**Issue by mrvisser** [oaeproject/Hilary#1217]
There is reason to believe there are issues w/ Cassandra 2.2 compatibility:

```
[2015-07-27T12:22:54.712Z] ERROR: oae-cassandra/4296 on MacBook-Air.local: An error occurred executing a cassandra query
    HelenusInvalidRequestException: CQL2 has been removed in Cassandra 2.2. Please use CQL3 instead
        at onReturn (/Users/stephen/Documents/Development/oae/Hilary/node_modules/helenus/lib/connection.js:420:23)
        at client._reqs.(anonymous function) (/Users/stephen/Documents/Development/oae/Hilary/node_modules/helenus/node_modules/helenus-thrift/lib/thrift/connection.js:80:11)
        at Object.CassandraClient.recv_execute_cql_query (/Users/stephen/Documents/Development/oae/Hilary/node_modules/helenus/lib/cassandra/Cassandra.js:8283:12)
        at /Users/stephen/Documents/Development/oae/Hilary/node_modules/helenus/node_modules/helenus-thrift/lib/thrift/connection.js:83:37
        at Socket.<anonymous> (/Users/stephen/Documents/Development/oae/Hilary/node_modules/helenus/node_modules/helenus-thrift/lib/thrift/transport.js:74:11)
        at Socket.emit (events.js:95:17)
        at Socket.<anonymous> (_stream_readable.js:765:14)
        at Socket.emit (events.js:92:17)
        at emitReadable_ (_stream_readable.js:427:10)
        at emitReadable (_stream_readable.js:423:5)
    --
    query: SELECT "columnfamily_name" FROM "system"."schema_columnfamilies" WHERE "keyspace_name" = ? AND "columnfamily_name" = ?
    --
    parameters: [
      "oae",
      "TenantNetworkTenants"
    ]
```

`cqlVersion` was confirmed to be set to `3.0.0`.

**Comment by nicolaasmatthijs** [comment]
@mrvisser : Given that @sathomas 's instance worked correctly after clearing the database, is this still an issue?

**Comment by sathomas** [comment]
It only worked after I cleared the database __and__ downgraded cassandra to 2.1.7

**Comment by nicolaasmatthijs** [comment]
@simong : Does this have any overlap with the work you're doing?
