### ISSUE TITLE
Pull passport-cas from npm

### ISSUE THREAD

**Issue by mrvisser** [oaeproject/Hilary#1219]
This PR: https://github.com/oaeproject/Hilary/pull/1210 caused a unit test regression:

```
  1) Authentication CAS authentication verify forward to cas:

      Uncaught AssertionError: '/cas/login' == '/cas/login/something/foo'
      + expected - actual

      -/cas/login
      +/cas/login/something/foo

      at /Users/branden/Source/apereo/oae/Hilary/node_modules/oae-authentication/tests/test-external-strategies.js:468:36
      at Request._callback (/Users/branden/Source/apereo/oae/Hilary/node_modules/oae-rest/lib/util.js:244:16)
      at Request.self.callback (/Users/branden/Source/apereo/oae/Hilary/node_modules/oae-rest/node_modules/request/request.js:121:22)
      at Request.emit (events.js:110:17)
      at Request.<anonymous> (/Users/branden/Source/apereo/oae/Hilary/node_modules/oae-rest/node_modules/request/request.js:978:14)
      at Request.emit (events.js:129:20)
      at IncomingMessage.<anonymous> (/Users/branden/Source/apereo/oae/Hilary/node_modules/oae-rest/node_modules/request/request.js:929:12)
      at IncomingMessage.emit (events.js:129:20)
      at _stream_readable.js:908:16
      at process._tickDomainCallback (node.js:381:11)
```

And so it was rolled back. This issue should be revisited to complete the work.

**Comment by mrvisser** [comment]
Assigned to @stuartf for fix

**Comment by mrvisser** [comment]
It looks like live changes of the loginPath weren't taking.

**Comment by stuartf** [comment]
Upstream hardcodes that path. I've made a PR at https://github.com/sadne/passport-cas/pull/11
