### ISSUE TITLE
(InvitingGuests) Server seems to not work after guest tenant is updated

### ISSUE THREAD

**Issue by mrvisser** [oaeproject/Hilary#1223]
```
[2015-08-04T15:08:44.761Z] ERROR: oae/8661 on qa1: An uncaught exception was raised to the application.
    TypeError: Cannot call method 'toLowerCase' of undefined
        at _storageHashToTenant (/opt/oae/node_modules/oae-tenants/lib/api.js:631:58)
        at _.chain.map.map.union.each.tenants.(anonymous function) (/opt/oae/node_modules/oae-tenants/lib/api.js:224:24)
        at Function._.map._.collect (/opt/oae/node_modules/underscore/underscore.js:172:24)
        at _.(anonymous function) [as map] (/opt/oae/node_modules/underscore/underscore.js:1496:34)
        at /opt/oae/node_modules/oae-tenants/lib/api.js:223:14
        at /opt/oae/node_modules/oae-util/lib/cassandra.js:787:16
        at onReturn (/opt/oae/node_modules/helenus/lib/connection.js:490:7)
        at onReturn (/opt/oae/node_modules/helenus/lib/connection.js:422:7)
        at client._reqs.(anonymous function) (/opt/oae/node_modules/helenus/node_modules/helenus-thrift/lib/thrift/connection.js:80:11)
        at Object.CassandraClient.recv_execute_cql3_query (/opt/oae/node_modules/helenus/lib/cassandra/Cassandra.js:8343:12)
[2015-08-04T15:10:06.380Z] ERROR: oae/8661 on qa1: An uncaught exception was raised to the application.
    TypeError: Cannot call method 'compact' of null
        at new module.exports.User (/opt/oae/node_modules/oae-principals/lib/model.user.js:55:26)
        at _hashToUser (/opt/oae/node_modules/oae-principals/lib/internal/dao.js:814:16)
        at /opt/oae/node_modules/oae-principals/lib/internal/dao.js:743:31
        at try_callback (/opt/oae/node_modules/redis/index.js:592:9)
        at RedisClient.return_reply (/opt/oae/node_modules/redis/index.js:685:13)
        at HiredisReplyParser.<anonymous> (/opt/oae/node_modules/redis/index.js:321:14)
        at HiredisReplyParser.EventEmitter.emit (events.js:95:17)
        at HiredisReplyParser.execute (/opt/oae/node_modules/redis/lib/parser/hiredis.js:43:18)
        at RedisClient.on_data (/opt/oae/node_modules/redis/index.js:547:27)
        at Socket.<anonymous> (/opt/oae/node_modules/redis/index.js:102:14)
```

**Comment by mrvisser** [comment]
Resolved in https://github.com/oaeproject/Hilary/commit/fa83d07
