### ISSUE TITLE
Investigate link preview processing errors

### ISSUE THREAD

**Issue by simong** [oaeproject/Hilary#1282]
There are quite a few errors in the production environment with regards to link preview processing.
Coincidentally, webshot 0.18.0 upgraded to PhantomJS 2.0 which might have something to do with it.

**Comment by simong** [comment]
Turns out that the failing content items are Collaborative documents. The errors look like:

```
[2016-04-13T14:35:27.420Z] ERROR: oae/3174 on pp0: An uncaught exception was raised to the application
    Error: spawn ENOENT
     at errnoException (child_process.js:980:11)
     at Process.ChildProcess._handle.onexit (child_process.js:771:34)
[2016-04-13T14:35:57.415Z] ERROR: oae-preview-processor/3174 on pp0: Could not generate a screenshot.
    Error: PhantomJS did not respond within the given timeout setting.
     at null._onTimeout (/opt/oae/node_modules/webshot/lib/webshot.js:225:19)
     at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
[2016-04-13T14:35:57.415Z] ERROR: oae-preview-processor/3174 on pp0: Could not generate an image (contentId=***************)
    err: {
      "code": 500,
      "msg": "PhantomJS did not respond within the given timeout setting."
    }
```

**Comment by simong** [comment]
Resolved by ensuring `phantomjs` got included in the build.
